version: "3"

services:

  front:
      build:
        context: .
        dockerfile: react-Dockerfile
      container_name: front_react
      restart: always
      image: react
      ports:
          - "3000:3000"
     
      volumes:
          - ./src/react-search:/app
          - /app/node_modules
      # networks:
      #   - my_network
  